### ISSUE TITLE
build.sh fails on linux with sed error

### ISSUE THREAD

**Issue by Stefan-Wagner** [masonicGIT/pacman#9] opened 2022-12-08 18:14 UTC
When running the build.sh on linux, I got an error: 

> sed: -e expression #1, char 1: unknown command: `.'

I could fix it, with altering the second to last sed command by removing the space after the -i-switch like this: 

```
from> sed -i '.bak' "s/last updated:[^<]*/last updated: $(date) -->/" index.htm

to  > > sed -i".bak" "s/last updated:[^<]*/last updated: $(date) -->/" index.htm
```

**Comment by masonicGIT** [comment] 2023-03-21 00:46
hello! thanks for finding this bug, want to submit a pull request with the fix?

**Comment by Stefan-Wagner** [comment] 2023-03-22 10:20
Well, yes, in principle. I haven't done a pull request before, so maybe you have to be a bit patient in guiding me. I already hit the "pull request" link at the top of the page (on the light blue bg, not at the absolute top with bg black), but didn't understand what to to then.

**Comment by cibersheep** [comment] 2023-03-22 10:50
> [...] you have to be a bit patient in guiding me. I already hit the "pull request" link at the top of the page (on the light blue bg, not at the absolute top with bg black), but didn't understand what to to then.

Hello. A pull request is more a:
- fork the original project into your own copy of the repo
- make modifications to the files of your copy of the repo
- commit and push the modification to your copy of the repo
- Pull Request the changes from your copy to the original repo

Maybe this guide can show some light: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by Stefan-Wagner** [comment] 2023-03-23 11:48
I see. Don't you think this is too much effort for a 1 single character fix? I would prefer, if you do the fix yourself and don't need a mention in the logs or somewhere.

**Comment by masonicGIT** [comment] 2023-05-16 02:05
Wasn't able to replicate this, so closing for now.

**Closed as completed by masonicGIT** 2023-05-16 02:05 UTC

**Comment by cibersheep** [comment] 2023-05-16 20:19
I can reproduce on Ubuntu 20,04

```
/pacman$ sh build.sh 
sed: -e expressió #1, caràcter 1: ordre desconeguda: «.»
```

```
$ sed --version
sed (GNU sed) 4.7
Packaged by Debian
```

As stated by Stefan, the issue is in https://github.com/masonicGIT/pacman/blob/master/build.sh#L87
`sed -i '.bak'` as the space behind `-i` is not recognized on Linux.

if changed by 
`sed --in-place='.bak' "s/last updated:[^<]*/last updated: $(date) -->/" index.html`
does still work on your system @masonicGIT ?
